import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";

import { AuthProvider } from "@/contexts/AuthProvider";

import Footer from "@/components/footer";
import Header from "@/components/header";

const roboto = Roboto({
  subsets: ["vietnamese"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["italic", "normal"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} flex flex-col bg-background text-[1.6rem] transition-colors duration-300 ease-in-out`}
      >
        <AuthProvider>
          <Header />
          <div className="group flex-1 pb-10">{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
